<?php

function title_case_menu() {
  $items = array();
  $items['title_case'] = array(
    'title' => 'Title Case Generator',
    'type' => MENU_NORMAL_ITEM,
    'access callback' => TRUE,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('title_case_form'),
  );

  $items['titled'] = array(
    'title' => 'Success',
    'type' => MENU_CALLBACK,
    'access callback' => TRUE,
    'page callback' => 'title_case_success',
  );
  return $items;
}

function title_case_form() {
  $form = array();
  $form['phrase'] = array(
    '#title' => 'Phrase input',
    '#type' => 'textfield',
    '#description' => t('Please enter a phrase'),
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Create title phrase',
  );

  return $form;
}

function title_case_form_submit($form, &$form_state) {
  $input_phrase = $form_state['values']['phrase'];
  $titled_phrase = ucwords($input_phrase);
  $_SESSION ['phrase_output'] = $titled_phrase;
  $form_state['redirect'] = 'titled';
}

function title_case_success() {
  $titled_phrase = $_SESSION['phrase_output'];
  return "Your titled phrase is : $titled_phrase";
}
