<?php
// function comment_buddy_menu() {
  // $items = array();
  // $items['comment_buddy'] = array(
  //   'title' => 'Comment Created!',
  //   'page callback' => 'create_confirmation',
  //   'access callback' => TRUE,
  //   'type' => MENU_CALLBACK,
  // );
  // return $items;
  // }
  //
  // function create_confirmation() {
  // }

function comment_buddy_comment_insert() {
  drupal_set_message("Thank you! Comment submitted!");
  // $_GET['destination'] = 'comment_buddy';
}

function comment_buddy_comment_update() {
  drupal_set_message('Your comment has been changed.');
}

function comment_buddy_comment_delete() {
  drupal_set_message('Comment deleted. Good work eating your words.');
}
